### ISSUE TITLE
Dockerfile das imagens e Aumentar o número de executor

### ISSUE THREAD

**Issue by Ostrock** [flaviostutz/spark-scala-jupyter#1]
Olá

Poderia disponibilizar os dockerfiles usados para criar as imagens que ele usa?
Hoje ele usa apenas um executor e gostaria de adicionar mais alguns para ter um melhor paralelismo.
Assim seria possível também usar o almond para mlehor suporte ao scala

Obrigado

**Comment by flaviostutz** [comment]
Olá!

De uma olhada no Dockerfile daqui: https://github.com/flaviostutz/spark-submit-scala/blob/master/Dockerfile

Veja se é o que vc precisa.

**Comment by Ostrock** [comment]
Sim, obrigado
